### ISSUE TITLE
[TRANSLATION] Missing Polish->English translation on Windows GCC Setup

### ISSUE THREAD

**Issue by DXPower** [PoetaKodu/CppLangNet#106]
### Description:

https://www.cpp-lang.net/tools/standalone/compilers/setup-gcc-windows/

One of the green helper cards has Polish in it. This should be translated to English.

"Przeczytaj poniższy artykuł by dowiedzieć się, jak dodać ścieżkę do zmiennej systemowej PATH:"

**Comment by PoetaKodu** [comment]
Thanks for reporting this issue.
Done: [commit preview](https://github.com/PoetaKodu/CppLangNet/commit/54212723d3f8155b550d9e44dc3d2ea1315cded9)
